# syntax=docker/dockerfile:1

FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /workspace

COPY src/api/src/worker/pom.xml src/api/src/worker/pom.xml
COPY src/api/src/worker/src src/api/src/worker/src

RUN mvn -f src/api/src/worker/pom.xml -DskipTests package

FROM eclipse-temurin:21-jre
WORKDIR /app

COPY --from=build /workspace/src/api/src/worker/target/*.jar /app/app.jar

ENTRYPOINT ["java","-jar","/app/app.jar"]
